### ISSUE TITLE
You could just iterate... backwards.

### ISSUE THREAD

**Issue by pjz** [AWegnerGitHub/awegnergithub.github.io-content#13]
The common solution for /2024_01_03_python_modify_list_while_iterating.md is to iterate backwards.  Deletes only change indices _after_ the deleted index, after all.   Note that this isn't as easy (or pretty) to do in python as a list comprehension, but it's not too bad:

````
len_nl = len(number_list)
for rindex in range(len_nl, 0, -1):
   value = number_list[rindex]
   if value < 5:
      del(numbers_list[rindex])

```

**Comment by AWegnerGitHub** [comment]
Sure, this is a possibility. I don't think this is the right way to do things with Python though. There are clearer ways to do this than deleting an index. The second variable and/or the list comprehension solutions I provided do this.

---

Your code has an `IndexError: list index out of range` error because the `rindex` starts at 9 when using the list I have as an example (`numbers_list = [0, 9, 2, 1, 5, 1, 10, 4, 3]`).

We could fix it by having `numbers_list[rindex-1]` on the `value=` and `del()` lines, but that makes it even less easy to follow. 

The modified function:

```
numbers_list = [0, 9, 2, 1, 5, 1, 10, 4, 3]
len_nl = len(numbers_list)
for rindex in range(len_nl, 0, -1):
   value = numbers_list[rindex-1]
   if value < 5:
      del(numbers_list[rindex-1])

print(numbers_list)
```

Outputs the expected `[9, 5, 10]`, but I think the two options I provided - using a second variable or the list comprehension - are clearer to a second developer looking at the code. 

---

I appreciate the input @pjz and am happy to add an another way to accomplish this task to the article, if it's clear to a newer developer what's occurring.
